# Generated by Django 4.1.4 on 2023-01-11 15:19

import datetime
from django.db import migrations, models
import django.utils.timezone
import myapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmem', models.CharField(max_length=50, verbose_name='使用者名稱')),
                ('bname', models.CharField(max_length=50, null=True, verbose_name='商品名稱')),
                ('num', models.IntegerField(verbose_name='數量')),
                ('ex', models.IntegerField(verbose_name='支出')),
                ('left', models.IntegerField(verbose_name='剩餘點數')),
                ('bid', models.UUIDField(default=uuid.uuid4, verbose_name='訂單編號')),
                ('bdate', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 15, 19, 23, 438287, tzinfo=datetime.timezone.utc), verbose_name='兌換日期')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LOGIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FKcheck', models.CharField(default=myapp.models.UUIDrand, max_length=36)),
                ('Rstate', models.CharField(max_length=42)),
                ('Raccesscode', models.CharField(max_length=43)),
            ],
        ),
        migrations.CreateModel(
            name='MEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.CharField(max_length=100)),
                ('PHONE', models.CharField(max_length=10, null=True, verbose_name='手機')),
                ('NAME', models.CharField(max_length=10, null=True, verbose_name='姓名')),
                ('PASSWORD', models.CharField(max_length=20, null=True, verbose_name='密碼')),
                ('NICKNAME', models.CharField(max_length=20, null=True, verbose_name='暱稱')),
                ('POINT', models.CharField(blank=True, max_length=30, null=True, verbose_name='點數')),
                ('IDCARD', models.CharField(max_length=10, null=True, verbose_name='身分證')),
                ('ACCESSCODE', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDID', models.CharField(max_length=50, verbose_name='訂單編號')),
                ('MEMID', models.CharField(default='', max_length=50, verbose_name='使用者編號')),
                ('APPID', models.CharField(default='', max_length=50, verbose_name='APP編號')),
                ('C_AMOUNT', models.CharField(default='', max_length=50, verbose_name='花費碳稅')),
                ('GPOINT', models.IntegerField(verbose_name='獲得點數')),
                ('AMOUNT', models.CharField(default='', max_length=50, verbose_name='消費總金額')),
                ('CDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='成立時間')),
            ],
        ),
        migrations.CreateModel(
            name='qa',
            fields=[
                ('MEMID', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='會員ID')),
                ('DISC', models.TextField(default='', max_length=255, verbose_name='問題描述')),
                ('IMAGE', models.ImageField(blank=True, default='', max_length=1000, upload_to='', verbose_name='上傳圖片')),
                ('RDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='送出日期')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='reports/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='REWARD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_ID', models.CharField(max_length=50, verbose_name='商品ID')),
                ('R_NAME', models.CharField(max_length=50, verbose_name='商品名稱')),
                ('R_IMG', models.ImageField(upload_to='static/images', verbose_name='商品img')),
                ('R_CONTENT', models.CharField(default='', max_length=50, verbose_name='商品內容')),
                ('COSTPOINT', models.CharField(default='', max_length=50, verbose_name='商品點數')),
                ('ALERT', models.CharField(default='', max_length=50, verbose_name='兌換警告')),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.CharField(max_length=100)),
                ('ACCESSCODE', models.CharField(max_length=100)),
            ],
        ),
    ]
